# Generated by Django 4.2.29 on 2026-03-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_company_is_verified'),
        ('orders', '0002_remove_order_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.service'),
        ),
    ]
